title: Feature Blog
email: lav.kumar.dev@gmail.com
description: >
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
include: ['_pages']

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

# Outputting
#permalink:     /:title.html

gems: [jekyll-paginate]
paginate: 2
paginate_path: "/page:num/"
